CREATE TABLE `fpcy_baiwang_request_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `requestId` varchar(64) DEFAULT NULL COMMENT '请求id(框架生成id)',
  `invoiceNum` varchar(10) DEFAULT NULL COMMENT '发票号码',
  `invoiceCode` varchar(20) DEFAULT NULL COMMENT '发票代码',
  `invoiceName` varchar(100) DEFAULT NULL COMMENT '发票类型名称',
  `requestType` char(10) DEFAULT NULL COMMENT '请求类型 cy：发票请求  ct:token请求',
  `requestConent` text COMMENT '查验参数',
  `errorMsg` longtext COMMENT '错误结果',
  `errorCode` varchar(1000) DEFAULT NULL COMMENT '错误信息代码',
  `requestTime` varchar(10) DEFAULT NULL COMMENT '请求时长',
  `isSuccess` char(1) DEFAULT NULL COMMENT '是否发送成功 Y：是 N：否',
  `comeFromCode` char(1) DEFAULT NULL COMMENT '来源',
  `inputTime` datetime DEFAULT NULL COMMENT '录入时间',
  PRIMARY KEY (`id`),
  KEY `idx_frl_ic_in` (`invoiceCode`,`invoiceNum`),
  KEY `idx_frl_int` (`inputTime`),
  KEY `idx_frl_inname` (`invoiceName`),
  KEY `idx_frl_requestid` (`requestId`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='发票_百望请求_流水';